### ISSUE TITLE
Ux cli desing improvment/errors

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/js-sdk#9]
- [ ] `*:*` - parse flags fails when given before arguments
- [x] `*:*` - print help for `command:` - for example when someone type `cli service` it prints help for service subcommands, but `service:` gives warning https://github.com/oclif/plugin-help/issues/42
```
./bin/run service:
 ›   Warning: service: is not a mesg-cli command.
Did you mean service:rm? [y/n]: 
 ›   Error: Run mesg-cli help service for a list of available commands.
```
- [x] `*:*` - a suggestion for invalid command is displayed only for few seconds https://github.com/oclif/plugin-not-found/issues/29
- [x] `*:*` - use only lower|upper case letter when start flags help description https://github.com/mesg-foundation/cli/pull/90
- [x] `*:*` - use `...` for one or more arguments (see: http://docopt.org/) https://github.com/mesg-foundation/cli/pull/91
- [ ] `*:*` - UnhandledPromiseRejectionWarning probably on all api calls. you can test it by setting iptables to drop traffic to ipfs.app.mesg.com or to localhost:50052
- [x] `*:*` - remove `--silent` option and leave only `-q|--quiet` or vice versa https://github.com/mesg-foundation/cli/pull/92
- [ ] `*:*` - do not make `--quiet` as gobal flag - pass it only for commands that can make use of it
- [x] `*:*` - `--quiet` - no help description https://github.com/mesg-foundation/cli/pull/92
- [ ] `*:*` - replace `--confirm` flag with `-y|--yes` as it's more common
- [x] `*:*` - s/Are you sure?:/Are you sure [y/n]?/ - remove `:` + add options to choose https://github.com/mesg-foundation/cli/issues/73
- [ ] `*:*` - print default value for argument/flag after the description, not before
- [ ] `*:*` - print required info  for argument/flag after the description, not before
- [ ] `daemon:logs` - print logs from the begging, but should print from moment it was called (and in general should have more flags like `service:logs` has)
- [ ] `service:list` - flag descirption `--sort=sort` - key should be renamed to column
- [x] `service:list` - no error|warning on invalid column to sort/display (flags `--sort` `--columns`) https://github.com/oclif/cli-ux/issues/115
- [ ] `service:list` - support `--cvs` format but cli dosen't need it, do it?
- [ ] `service:list` - no support `--json`
- [ ] `service:list` - flag `--no-truncate` dose not work
- [ ] `service:list` - flag `--extended` do nothing, so it should be removed. There is no extra column to display
- [ ] `service:dev` - hit ctrl+c when service run a long time or on engine exit
```
(node:12917) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
```
- [ ] `service:dev` - no cleanup handler on error
```
./bin/run service:dev ../test-service                                 
Create service... 39PfjfnVWSnNLFGc6jdwr88PZ6dbFfToTeiH84GdtxgV
Start instance... 4bNBqmJQoGKdHbtdY6Dtushy1aMdnLDtnA1U4EBt35Vr
Error: cannot ...
./bin/run service:dev ../test-service
Create service... !
Error: 2 UNKNOWN: service "39PfjfnVWSnNLFGc6jdwr88PZ6dbFfToTeiH84GdtxgV" already exists
```

- [ ] `servcie:compile` - missing option `--oneline` for printing json as one liner
- [ ] `servcie:compile` - no option for get `source` from ipfs
- [ ] `service:doc` - extra empty lines between header task/events and table
- [x] `service:doc` - no info about possible env variables in readme https://github.com/mesg-foundation/cli/issues/23
- [x] `service:doc` - in alias section `service:doc` is repeated - should be removed https://github.com/mesg-foundation/cli/pull/89
- [ ] `service:doc` - update command description to "Generate the documentation for the service" (remove the part about readme file, because it just works with `--save` flag)
- [ ] `service:doc` - update `--save` flag description to "save documentation to README.md`
- [ ] `service:doc` - `--save` overwrites an existing README.md without permission
- [ ] `service:logs` - `--no-follow` flag does not work
- [ ] `service:logs` - `--no-tail` flag does not work
- [ ] `service:logs` - `--task` or `--events` has no option to filter multiple tasks/events
- [ ] `service:start` - missing short flag (`-e`) for envs
- [x] `account:*` - try to invoce command with `--help` flag passed at the end (last one) - should display help message https://github.com/mesg-foundation/cli/pull/84/files
- [ ] `account:list` - has the same issues as `servcie:list` - columns/sort/no-truncate/extended`
- [x] `account:list` - remove ls alias https://github.com/mesg-foundation/cli/pull/89
- [x] `account:create` - can't specify passpharse flag - https://github.com/mesg-foundation/cli/pull/84

```
./bin/run --passphrase=1234 account:create
 ›   Warning: --passphrase=1234 is not a mesg-cli command.
Did you mean account:export? [y/n]: ^C
./bin/run account:create --passphrase=1234
 ›   Error: Unexpected argument: --passphrase=1234
 ›   See more help with --help
```

- [x] `marketplace:publish` - running in empty directory gives unclear error " TypeError: Cannot read property 'addresses' of undefined" https://github.com/mesg-foundation/cli/pull/86
- [x] `marketplace:*` - support `-p` short flag for passpharse while `account` does not https://github.com/mesg-foundation/cli/pull/84
- [x] `marketplace:*` - can't pass `--account` argument https://github.com/mesg-foundation/cli/pull/88

```
$./bin/run marketplace:publish -a 0x00bfd8604654210a52833fdf946d5c78f13e4ffc ../test-service
 ›   Error: Unexpected arguments: 0x00bfd8604654210a52833fdf946d5c78f13e4ffc, ../test-service
 ›   See more help with --help
$ ./bin/run marketplace:publish ../test-service -a 0x00bfd8604654210a52833fdf946d5c78f13e4ffc                
 ›   Error: Unexpected arguments: -a, 0x00bfd8604654210a52833fdf946d5c78f13e4ffc
 ›   See more help with --help
```
- [ ] `instance:*` - missing commands to manage instances - service:start|service:stop|service:logs should be moved under `instance` command

**Comment by antho1404** [comment]
Issue migrated to liteflow-labs/liteflow-js#22
